apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: authelia
type: Opaque
stringData:
  # Generate with: openssl rand -hex 32
  JWT_SECRET: "932e214af8516511175a1b22541d924938d48f5ab70f05dcc3015a580957babf"
  SESSION_SECRET: "29ef4f04b6a68310c4dcb0ff44cbe88c60db91e7d6d823d5ca67df49991dc26f"
  STORAGE_ENCRYPTION_KEY: "730e570e88d116c40a10ee059f58feab210d2f8ce9c32f5bea7924d42a63351a"
