apiVersion: apps/v1
kind: Deployment
metadata:
  name: rethinkdb
  namespace: stf
  labels:
    app: rethinkdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rethinkdb
  template:
    metadata:
      labels:
        app: rethinkdb
    spec:
      containers:
        - name: rethinkdb
          image: rethinkdb:2.4.2
          command:
            - rethinkdb
            - --bind
            - all
            - --cache-size
            - "2048"
          ports:
            - name: admin
              containerPort: 8080
              protocol: TCP
            - name: driver
              containerPort: 28015
              protocol: TCP
            - name: cluster
              containerPort: 29015
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rethinkdb-data
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rethinkdb
  namespace: stf
  labels:
    app: rethinkdb
spec:
  type: ClusterIP
  selector:
    app: rethinkdb
  ports:
    - name: admin
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: driver
      port: 28015
      targetPort: 28015
      protocol: TCP
    - name: cluster
      port: 29015
      targetPort: 29015
      protocol: TCP
