apiVersion: v1
kind: Service
metadata:
  name: stf
  namespace: stf
  labels:
    app: stf
spec:
  type: ClusterIP
  selector:
    app: stf
  ports:
    - name: web
      port: 7100
      targetPort: 7100
      protocol: TCP
    - name: websocket
      port: 7110
      targetPort: 7110
      protocol: TCP
    - name: provider-7400
      port: 7400
      targetPort: 7400
      protocol: TCP
    - name: provider-7401
      port: 7401
      targetPort: 7401
      protocol: TCP
    - name: provider-7402
      port: 7402
      targetPort: 7402
      protocol: TCP
    - name: provider-7403
      port: 7403
      targetPort: 7403
      protocol: TCP
    - name: provider-7404
      port: 7404
      targetPort: 7404
      protocol: TCP
    - name: provider-7405
      port: 7405
      targetPort: 7405
      protocol: TCP
