apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stf-ingress
  namespace: stf
  annotations:
    nginx.org/proxy-body-size: "100m"
    nginx.org/proxy-read-timeout: "3600s"
    nginx.org/proxy-send-timeout: "3600s"
    nginx.org/proxy-connect-timeout: "60s"
    nginx.org/websocket-services: "stf"
spec:
  ingressClassName: nginx
  rules:
    - host: stf.freedom35.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stf
                port:
                  number: 7100
