apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: stf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stf-auth
  template:
    metadata:
      labels:
        app: stf-auth
    spec:
      containers:
      - name: auth
        image: openstf/stf:latest
        envFrom:
        - configMapRef:
            name: stf-config
        env:
        - name: RETHINKDB_PORT_28015_TCP
          value: "tcp://rethinkdb:28015"
        command:
          - stf
          - auth-mock
          - --port
          - "3000"
          - --app-url
          - "$(STF_URL)"
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
