apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
  namespace: stf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stf-websocket
  template:
    metadata:
      labels:
        app: stf-websocket
    spec:
      containers:
      - name: websocket
        image: openstf/stf:latest
        envFrom:
        - configMapRef:
            name: stf-config
        env:
        - name: RETHINKDB_PORT_28015_TCP
          value: "tcp://rethinkdb:28015"
        command:
          - stf
          - websocket
          - --port
          - "3000"
          - --storage-url
          - "$(STORAGE_URL)"
          - --connect-sub
          - tcp://triproxy:7150
          - --connect-push
          - tcp://triproxy:7170
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
