apiVersion: v1
kind: Service
metadata:
  name: rethinkdb
  namespace: stf
spec:
  type: ClusterIP
  ports:
  - name: cluster
    port: 29015
    targetPort: 29015
    protocol: TCP
  - name: driver
    port: 28015
    targetPort: 28015
    protocol: TCP
  - name: admin
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: rethinkdb
