apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anonaddy
  namespace: anonaddy
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - anonaddy.yourdomain.com
      secretName: anonaddy-tls
  rules:
    - host: anonaddy.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: anonaddy
                port:
                  number: 8000
