apiVersion: v1
kind: Service
metadata:
  name: provider
  namespace: stf
spec:
  type: NodePort
  ports:
  - name: screen-ws
    port: 7400
    targetPort: 7400
    nodePort: 30740
    protocol: TCP
  - name: screen-port-range-start
    port: 15000
    targetPort: 15000
    nodePort: 30150
    protocol: TCP
  selector:
    app: stf-provider
